services:
  postgres:
    image: postgres:16-alpine
    container_name: kailes_treks_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s@01
      POSTGRES_DB: VKT_trekking_v2_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d VKT_trekking_v2_demo"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
