import type { Trekking } from "@prisma/client";
import { Button } from "@/components/ui/button";
import { FormInput, FormSelect, FormTextarea } from "@/components/shared/form-controls";
import { ImageUploader } from "@/components/shared/image-uploader";
import { RichTextEditor } from "@/components/shared/rich-text-editor";
import { saveTrekking } from "@/app/admin/trekking/actions";

export function TrekkingForm({ trek }: { trek?: Trekking | null }) {
  return <form action={saveTrekking} className="grid gap-6 rounded-2xl border bg-white p-6"><input type="hidden" name="id" value={trek?.id ?? ""} /><div className="grid gap-6 md:grid-cols-2"><FormInput label="Name" name="name" defaultValue={trek?.name ?? ""} required /><FormInput label="Slug" name="slug" defaultValue={trek?.slug ?? ""} required /><FormInput label="Destination" name="destination" defaultValue={trek?.destination ?? ""} required /><FormInput label="Region" name="region" defaultValue={trek?.region ?? ""} /><FormInput label="Duration days" name="durationDays" type="number" defaultValue={trek?.durationDays ?? 1} /><FormInput label="Max altitude meters" name="maxAltitudeMeters" type="number" defaultValue={trek?.maxAltitudeMeters ?? 0} /><FormSelect label="Difficulty" name="difficultyLevel" defaultValue={trek?.difficultyLevel ?? "Moderate"} options={["Easy", "Moderate", "Challenging", "Difficult", "Extreme"].map((x) => ({ label: x, value: x }))} /><FormSelect label="Status" name="status" defaultValue={trek?.status ?? "Draft"} options={["Draft", "Published", "Archived"].map((x) => ({ label: x, value: x }))} /><FormInput label="Price" name="price" type="number" step="0.01" defaultValue={trek?.price?.toString() ?? ""} /><FormInput label="Currency" name="currencyCode" defaultValue={trek?.currencyCode ?? "USD"} /><FormInput label="Ordering" name="ordering" type="number" defaultValue={trek?.ordering ?? 0} /><ImageUploader defaultValue={trek?.heroImageUrl} /></div><FormTextarea label="Short description" name="shortDescription" defaultValue={trek?.shortDescription ?? ""} required /><RichTextEditor label="Overview" name="overview" defaultValue={trek?.overview} /><div className="grid gap-6 md:grid-cols-2"><FormInput label="SEO title" name="seoTitle" defaultValue={trek?.seoTitle ?? ""} /><FormTextarea label="SEO description" name="seoDescription" defaultValue={trek?.seoDescription ?? ""} /></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="featured" defaultChecked={trek?.featured ?? false} /> Featured</label><Button className="w-fit">Save package</Button></form>;
}
