using TravelCleanArch.Domain.Enumerations;

namespace TravelCleanArch.Application.Abstractions.Travel;

public sealed record TrekkingTypeImageDto(int Id, string FilePath, string? AltText, int SortOrder, bool IsCover);
public sealed record TrekkingTypeDto(int Id, string Title, string ShortDescription, string? Description, string? ImagePath, int Ordering, bool IsPublished, IReadOnlyCollection<TrekkingTypeImageDto>? Images = null);
public sealed record TrekkingTypeUpsertDto(string Title, string ShortDescription, string? Description, string? ImagePath, int Ordering, bool IsPublished, IReadOnlyCollection<TrekkingTypeImageDto>? Images = null);

public sealed record TrekkingListItemDto(
    int Id,
    string Name,
    string HeroImageUrl,
    string Slug,
    string ShortDescription,
    string Destination,
    int DurationDays,
    decimal Price,
    string Status,
    bool Featured,
    int Ordering,
    int? TrekkingTypeId,
    string? TrekkingTypeTitle,
    string? DifficultyLevel,
    string? Country);

public sealed record TrekkingFaqDto(int Id, string Question, string Answer, int Ordering);
public sealed record TrekkingMediaDto(int Id, string Url, string? Caption, string MediaType, int Ordering, string? FilePath = null, string? VideoUrl = null);
public sealed record TrekkingItineraryDayDto(int Id, int TrekkingItineraryId, int DayNumber, string? ShortDescription, string? Description, string? Meals, string? AccommodationType);
public sealed record TrekkingItineraryDto(int Id, string SeasonName, int SortOrder, IReadOnlyCollection<TrekkingItineraryDayDto> Days);
public sealed record TrekkingMapDto(int Id, string FilePath, string? Title, string? Notes);
public sealed record TrekkingCostItemDto(int Id, string Title, string? ShortDescription, bool IsActive, string Type, int SortOrder);
public sealed record TrekkingFixedDepartureDto(int Id, DateTime StartDate, DateTime EndDate, int ForDays, DepartureStatus Status, int? GroupSize);
public sealed record TrekkingGearListDto(int Id, string? ShortDescription, string FilePath, string? ImagePath);
public sealed record TrekkingHighlightDto(int Id, string Text, int SortOrder);
public sealed record TrekkingReviewDto(int Id, string FullName, string EmailAddress, string? UserPhotoPath, string? VideoUrl, int Rating, string ReviewText, string ModerationStatus);

public sealed record TrekkingUpsertDto(
    string Name,
    string? Slug,
    string ShortDescription,
    string Destination,
    string? Region,
    int DurationDays,
    int MaxAltitudeMeters,
    int? MaxAltitudeFeet,
    string Difficulty,
    string? BestSeason,
    string? Overview,
    string? Inclusions,
    string? Exclusions,
    string? HeroImageUrl,
    string? HeroVideoUrl,
    string? Permits,
    int MinGroupSize,
    int MaxGroupSize,
    bool PriceOnRequest,
    decimal? Price,
    string? CurrencyCode,
    string? PriceNotesUrl,
    string? TripPdfUrl,
    string? AvailableDates,
    string? BookingCtaUrl,
    string? SeoTitle,
    string? SeoDescription,
    string Status,
    bool Featured,
    int Ordering,
    string? SummitRoute,
    bool RequiresClimbingPermit,
    string? ExpeditionStyle,
    bool OxygenSupport,
    bool SherpaSupport,
    decimal? SummitBonusUsd,
    int? TrekkingTypeId,
    IReadOnlyCollection<TrekkingFaqDto> Faqs,
    IReadOnlyCollection<TrekkingMediaDto> MediaItems,
    string? OverviewCountry = null,
    string? PeakName = null,
    string? OverviewDuration = null,
    string? Route = null,
    string? Rank = null,
    decimal? Latitude = null,
    decimal? Longitude = null,
    string? CoordinatesText = null,
    string? WeatherReport = null,
    string? Range = null,
    string? WalkingPerDay = null,
    string? Accommodation = null,
    string? GroupSizeText = null,
    string? DifficultyLevel = null,
    string? BoardBasis = null,
    decimal? AverageRating = null,
    string? RatingLabel = null,
    int? ReviewCount = null,
    IReadOnlyCollection<TrekkingItineraryDto>? Itineraries = null,
    IReadOnlyCollection<TrekkingMapDto>? Maps = null,
    IReadOnlyCollection<TrekkingCostItemDto>? CostItems = null,
    IReadOnlyCollection<TrekkingFixedDepartureDto>? FixedDepartures = null,
    IReadOnlyCollection<TrekkingGearListDto>? GearLists = null,
    IReadOnlyCollection<TrekkingHighlightDto>? Highlights = null,
    IReadOnlyCollection<TrekkingReviewDto>? Reviews = null);

public sealed record TrekkingDetailsDto(
    int Id,
    string Name,
    string Slug,
    string ShortDescription,
    string Destination,
    string? Region,
    int DurationDays,
    int MaxAltitudeMeters,
    int? MaxAltitudeFeet,
    string Difficulty,
    string? BestSeason,
    string? Overview,
    string? Inclusions,
    string? Exclusions,
    string? HeroImageUrl,
    string? HeroVideoUrl,
    string? Permits,
    int MinGroupSize,
    int MaxGroupSize,
    bool PriceOnRequest,
    decimal? Price,
    string? CurrencyCode,
    string? PriceNotesUrl,
    string? TripPdfUrl,
    string? AvailableDates,
    string? BookingCtaUrl,
    string? SeoTitle,
    string? SeoDescription,
    string Status,
    bool Featured,
    int Ordering,
    string? SummitRoute,
    bool RequiresClimbingPermit,
    string? ExpeditionStyle,
    bool OxygenSupport,
    bool SherpaSupport,
    decimal? SummitBonusUsd,
    int? TrekkingTypeId,
    string? TrekkingTypeTitle,
    IReadOnlyCollection<TrekkingFaqDto> Faqs,
    IReadOnlyCollection<TrekkingMediaDto> MediaItems,
    string? OverviewCountry,
    string? PeakName,
    string? OverviewDuration,
    string? Route,
    string? Rank,
    decimal? Latitude,
    decimal? Longitude,
    string? CoordinatesText,
    string? WeatherReport,
    string? Range,
    string? WalkingPerDay,
    string? Accommodation,
    string? GroupSizeText,
    string? DifficultyLevel,
    string? BoardBasis,
    decimal? AverageRating,
    string? RatingLabel,
    int? ReviewCount,
    IReadOnlyCollection<TrekkingItineraryDto> Itineraries,
    IReadOnlyCollection<TrekkingMapDto> Maps,
    IReadOnlyCollection<TrekkingCostItemDto> CostItems,
    IReadOnlyCollection<TrekkingFixedDepartureDto> FixedDepartures,
    IReadOnlyCollection<TrekkingGearListDto> GearLists,
    IReadOnlyCollection<TrekkingHighlightDto> Highlights,
    IReadOnlyCollection<TrekkingReviewDto> Reviews);

public sealed record TrekkingPagedResult(IReadOnlyCollection<TrekkingListItemDto> Items, int Page, int PageSize, int TotalCount);
