using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TravelCleanArch.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class HeroWhyus : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                @"CREATE TABLE IF NOT EXISTS company_why_with_us_hero (
                    \"Id\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    \"Header\" character varying(200) NOT NULL,
                    \"Title\" character varying(200) NOT NULL,
                    \"Description\" character varying(4000) NOT NULL,
                    \"BackgroundImagePath\" character varying(500),
                    \"UpdatedAtUtc\" timestamp with time zone NOT NULL,
                    \"CreatedBy\" integer,
                    \"UpdatedBy\" integer
                );");

            migrationBuilder.Sql(
                @"ALTER TABLE company_why_with_us_hero
                    ADD COLUMN IF NOT EXISTS \"CreatedAtUtc\" timestamp with time zone NOT NULL
                    DEFAULT TIMESTAMPTZ '0001-01-01 00:00:00+00';");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "CreatedAtUtc",
                table: "company_why_with_us_hero");
        }
    }
}
